<?php

/**
 * @file
 * Contains acro_orange_layouts.module.
 */

/**
 * Implements hook_theme().
 */
function acro_orange_layouts_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__full' => [
      'path' => $path . '/templates/paragraphs',
      'template' => 'paragraph--full',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 */
function acro_orange_layouts_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];

  if ($paragraph_bundle_label = $paragraph->type->entity->label()) {
    $variables['bundle_label'] = $paragraph_bundle_label;
  }
}

/**
 * Implements hook_page_attachments().
 */
function acro_orange_layouts_page_attachments(array &$attachments) {
  // Add libraries if on admin routes.
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'acro_orange_layouts/admin';
    $attachments['#attached']['library'][] = 'acro_orange_layouts/orange-layouts';
  }
}
